import { Box, Button, Flex, Heading, useColorMode } from "@chakra-ui/react";
import Head from "next/head";

const Home = () => {
  const { toggleColorMode } = useColorMode();

  return (
    <Box>
      <Head>
        <title>Create Chakra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column" alignItems="center" w="100vw" h="100vh" p="16">
        <Button onClick={toggleColorMode}>Toggle Color Mode</Button>
        <Heading as="h1">Solana Base App (Next.js + Chakra UI)</Heading>
      </Flex>
    </Box>
  );
};

export default Home;
