import { Box, Heading, VStack } from "@chakra-ui/react";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";
import Head from "next/head";
import Balance from "../components/Balance/Balance";

const Home = () => {
  const { connection } = useConnection();
  const { publicKey } = useWallet();

  return (
    <>
      <Head>
        <title>Create Chakra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack alignItems="center" px={[8, 24, 48]}>
        <Heading as="h1">Solana Base App (Next.js + Chakra UI)</Heading>
        {publicKey && <Balance w="full" pt={16} />}
      </VStack>
    </>
  );
};

export default Home;
